server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:outsera
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    org.springframework: INFO
