openapi: 3.1.0
info:
  title: Golden Raspberry Awards
  version: v1
servers:
  - url: http://localhost:8080
    description: Local server url
paths:
  /intervals:
    get:
      tags:
        - interval-controller
      operationId: getIntervals
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    $ref: '#/components/schemas/ProducerInterval'
components:
  schemas:
    ProducerInterval:
      type: object
      properties:
        producer:
          type: string
        interval:
          type: integer
          format: int32
        previousWin:
          type: integer
          format: int32
        followingWin:
          type: integer
          format: int32
